#!/usr/bin/env python3
"""
Output cleaner - Post-process converted Markdown/JSON for better quality.
"""

import re
from pathlib import Path
from typing import List, Optional


def clean_markdown(text: str) -> str:
    """Clean and normalize Markdown output."""
    # Remove excessive blank lines
    text = re.sub(r'\n{4,}', '\n\n\n', text)
    
    # Fix spacing around headers
    text = re.sub(r'\n(#{1,6}\s)', r'\n\n\1', text)
    text = re.sub(r'(#{1,6}\s.*)\n\n+', r'\1\n', text)
    
    # Fix list indentation
    text = re.sub(r'^(\s*)- ', r'\1- ', text, flags=re.MULTILINE)
    
    # Clean up code blocks
    text = re.sub(r'```\n\n', '```\n', text)
    
    return text.strip()


def fix_table_formatting(text: str) -> str:
    """Fix common table formatting issues."""
    lines = text.split('\n')
    result = []
    
    i = 0
    while i < len(lines):
        line = lines[i]
        
        # Detect table start (has |)
        if '|' in line and line.strip().startswith('|'):
            table_lines = [line]
            i += 1
            
            # Collect all table rows
            while i < len(lines) and '|' in lines[i]:
                table_lines.append(lines[i])
                i += 1
            
            # Process table
            result.extend(_process_table(table_lines))
        else:
            result.append(line)
            i += 1
    
    return '\n'.join(result)


def _process_table(lines: List[str]) -> List[str]:
    """Process a table block."""
    if len(lines) < 2:
        return lines
    
    # Check if separator exists
    has_sep = any('---' in l or '===' in l for l in lines[1:2])
    
    if not has_sep:
        # Add separator after header
        header = lines[0]
        cols = header.count('|') + 1
        sep = '| ' + ' | '.join(['---'] * (cols - 1)) + ' |'
        lines.insert(1, sep)
    
    return lines


def remove_metadata_blocks(text: str) -> str:
    """Remove common metadata/boilerplate blocks."""
    patterns = [
        r'---\s*\n.*?\n---',  # YAML frontmatter
        r'^\s*Generated by.*$',  # Generator comments
        r'^\s*Created:.*$',  # Creation dates
    ]
    
    for p in patterns:
        text = re.sub(p, '', text, flags=re.MULTILINE)
    
    return text


def normalize_encoding(text: str) -> str:
    """Normalize text encoding issues."""
    # Fix common encoding problems
    replacements = {
        '\u2018': "'",  # smart apostrophe
        '\u2019': "'",
        '\u201c': '"',  # smart quote
        '\u201d': '"',
        '\u2013': '-',  # en dash
        '\u2014': '--', # em dash
        '\u2026': '...', # ellipsis
        '\u00a0': ' ',   # non-breaking space
    }
    
    for old, new in replacements.items():
        text = text.replace(old, new)
    
    return text


def clean_output(
    input_path: str,
    output_path: Optional[str] = None,
    fix_tables: bool = True,
    remove_meta: bool = True
) -> str:
    """
    Clean converted output.
    
    Args:
        input_path: Path to input Markdown file
        output_path: Optional output path (overwrites if not provided)
        fix_tables: Fix table formatting
        remove_meta: Remove metadata blocks
        
    Returns:
        Cleaned text
    """
    text = Path(input_path).read_text(encoding='utf-8')
    
    if remove_meta:
        text = remove_metadata_blocks(text)
    
    if fix_tables:
        text = fix_table_formatting(text)
    
    text = clean_markdown(text)
    text = normalize_encoding(text)
    
    if output_path:
        Path(output_path).write_text(text, encoding='utf-8')
    
    return text


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Clean Markdown output")
    parser.add_argument("input", help="Input Markdown file")
    parser.add_argument("-o", "--output", help="Output file (default: overwrite input)")
    parser.add_argument("--no-table-fix", action="store_true", help="Skip table fixes")
    parser.add_argument("--no-meta", action="store_true", help="Skip metadata removal")
    args = parser.parse_args()
    
    clean_output(
        args.input,
        args.output,
        fix_tables=not args.no_table_fix,
        remove_meta=not args.no_meta
    )
    print(f"Cleaned: {args.output or args.input}")