SELECT
  TABLE_SCHEMA,
  TABLE_NAME,
  ORDINAL_POSITION,
  COLUMN_NAME,
  DATA_TYPE,
  COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = '{{database}}'
  AND TABLE_NAME = 'gh_hg_bscyearall_dues'
ORDER BY ORDINAL_POSITION;
